services:
  aset:
    build:
      context: https://github.com/alexmarcel/mapped-asset-manager.git#main
      dockerfile: Dockerfile
    container_name: aset
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      APP_URL: https://aset.alexmarcel.com
      UPLOAD_DIR: /app/data/uploads
    volumes:
      - ./data:/app/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aset.rule=Host(`aset.alexmarcel.com`)"
      - "traefik.http.routers.aset.entrypoints=websecure"
      - "traefik.http.routers.aset.tls.certresolver=myresolver"
      - "traefik.http.services.aset.loadbalancer.server.port=3000"

networks:
  web:
    external: true
